#!/usr/bin/env python
#

from os                                 import getenv, path, getcwd
from lib.argparse                       import ArgumentParser, RawDescriptionHelpFormatter
from logging                            import error, info, basicConfig, INFO, DEBUG

from lib.shell                          import ShellError, ShellTimeoutError, ssh, Shell
from lib.provisioning                   import Provisioner
from lib.exceptions                     import ErrorExit

# RemoteHost
#
class RemoteHost():
    def __init__(s, hostname):
        s.__hostname = hostname
        s.__ssh_quiet = True

    def ssh(s, cmd, quiet=False, ignore_result=False):
        result, output = Shell.ssh(s.__hostname, cmd, quiet=quiet or s.__ssh_quiet, ignore_result=ignore_result)
        return result, output

# BootspeedTest
#
class BootspeedTest():
    '''
    Handle all the tasks for getting a test system fully up and installed and ready for
    running the kernel tests.
    '''

    # __init__
    #
    def __init__(s, args):
        s.args = args
        s.__hwdb = None
        s.target = s.args.target[0]
        s.sut = RemoteHost(s.args.target[0])
        s.__rcwd = None

    @property
    def rcwd(s):
        if s.__rcwd is None:
            result, output = s.sut.ssh('echo cwd: \\$\\(pwd\\)')
            for line in output:
                if 'cwd:' in line:
                    (junk, cwd) = line.split(':')
                    s.__rcwd = cwd.strip()
        return s.__rcwd

    def rdir(s, index):
        return path.join(s.rcwd, 'results', '%d' % index)

    def produce_error_results(s, workspace, msg):
        with open(path.join(workspace, 'kernel-results.xml'), 'w') as f:
            f.write('<testsuites>\n')
            f.write('    <testsuite tests="1" errors="1" name="Provisioning" timestamp="2012-01-01" hostname="hostname" time="0" failures="0">\n')
            f.write('        <properties/>\n')
            f.write('        <testcase classname="Provisioning.Initial-Provisioning" name="provisioning" time="0.0">\n')
            f.write('            <error message="Provisioning failed!" type="Logparse">\n')
            f.write(msg)
            f.write('\n')
            f.write('            </error>\n')
            f.write('        </testcase>\n')
            f.write('    </testsuite>\n')
            f.write('</testsuites>\n')

    # install_bootspeed_pkg
    #
    def install_bootspeed_pkg(s):
        '''
        Perform a update of the kernels on a remote system.
        '''
        s.sut.ssh('sudo apt-get update', ignore_result=True)
        s.sut.ssh('sudo apt-get --yes --force-yes install bootchart dpkg-dev')

    # configure_kernel_boot_parameters
    #
    def configure_kernel_boot_parameters(s):
        s.sut.ssh(r'sudo sed -i \'s/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="initcall_debug quiet printk.time=1"/\' /etc/default/grub')

    # process_bootspeed_results
    #
    def process_bootspeed_results(s, index):
        p = s.rdir(index)
        s.sut.ssh('mkdir -p %s' % p)

        result, output = s.sut.ssh('ls /var/log/bootchart/*.tgz | sort -Vr | head -1')
        for line in output:
            if 'bootchart' in line:
                fid = line.strip()
        for fmt in ['png', 'svg']:
            s.sut.ssh('sudo bootchart --quiet --format=%(fmt)s --crop-after=gnome-panel,mutter,unity-panel-service --annotate=ureadahead,mountall,hostname,hwclock --annotate=Xorg  --annotate=gnome-session  --annotate-file=%(p)s/times --output=%(p)s/bootchart.%(fmt)s %(fid)s' % vars())

        s.sut.ssh('cp %(fid)s %(p)s' % vars())
        s.sut.ssh('sudo lspci -vvv \> %s/lscpci' % p)
        s.sut.ssh('sudo cp /var/log/dmesg %s' % p)
        s.sut.ssh('sudo chmod +r %s/dmesg' % p)
        s.sut.ssh('sudo cp /var/log/syslog %s' % p)
        s.sut.ssh('sudo chmod +r %s/syslog' % p)
        s.sut.ssh('sudo tar czvf %s/installer.tgz /var/log/installer/' % p)

    # main
    #
    def main(s):
        retval = 1
        try:
            s.install_bootspeed_pkg()
            s.configure_kernel_boot_parameters()

            Provisioner.reboot(s.target) # package installed
            #Provisioner.reboot(s.target) # readahead should be settled down

            # Collect bootspeed data for some number of runs
            #
            for i in range(1,11):
                info('Bootspeed data collection run (%d)' % i)
                #Provisioner.reboot(s.target)
                s.process_bootspeed_results(i)

            retval = 0

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            print("Aborting ...")

        except ShellTimeoutError as e:
            msg = 'The command (%s) timed out. (%d)' % (e.cmd, e.timeout)
            ws = getenv('WORKSPACE')
            if ws is not None:
                s.produce_error_results(ws, msg)
            error(msg)

        except ShellError as e:
            msg = 'The command (%s) returned a non-zero exit status (%d).\n' % (e.cmd, e.returncode)
            for line in e.output:
                msg += line.rstrip() + '\n'

            error('The command (%s) returned a non-zero exit status (%d).' % (e.cmd, e.returncode))
            for line in e.output:
                error(line.rstrip())

            ws = getenv('WORKSPACE')
            if ws is not None:
                s.produce_error_results(ws, msg)

        except ErrorExit as e:
            error(e.message)
            ws = getenv('WORKSPACE')
            if ws is not None:
                s.produce_error_results(ws, e.message)
            pass

        if retval > 0:
            error("")
            error("Due to the above error(s), this script is unable to continue and is terminating.")
            error("")

        return retval

if __name__ == '__main__':
    if getenv('DEBUG'):
        LOGLEVEL = DEBUG
    else:
        LOGLEVEL = INFO
    basicConfig(level=LOGLEVEL, format="%(levelname)s - %(message)s")

    app_description = '''
    '''

    app_epilog = '''
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('target', metavar='TARGET', type=str, nargs=1, help='The name of the system that has been provisioned and we want to run the bootspeed tests on.')

    args = parser.parse_args()

    app = BootspeedTest(args)
    exit(app.main())

# vi:set ts=4 sw=4 expandtab syntax=python:
