#!/bin/sh
# Start the daemon in the background.
flock -nx /tmp/kmsgq-launchpad.lck -c "$HOME/shankbot/kernel-testing/kmsgq-launchpad $"

# Attempt to re-grab an exclusive lock, if this succeeds
# then the daemon has failed to start.  Timeout after 5s.
flock -w 5 -x /tmp/kmsgq-jenkins -c "exit 0" || \
    $HOME/bin/dashboard-status kmsgq-launchpad 'Kernel Testing' 'Kernel MsgQueue Launchpad' 5m 30m
