#!/bin/sh

# Start the daemon in the background.
flock -nx /tmp/kmsgq-ircbot.lck -c "$HOME/shankbot/kernel-testing/kmsgq-ircbot kernel-irc &"

# Attempt to re-grab an exclusive lock, if this succeeds
# then the daemon has failed to start.  Timeout after 5s.
flock -w 5 -x /tmp/kmsgq-shiv.lck -c "exit 0" || \
    $HOME/bin/dashboard-status kmsgq-ircbot 'Kernel Testing' 'Kernel MsgQueue Ircbot' 5m 30m
