#!/usr/bin/env python
#
# This application takes a list json file as input. That json file
# contains a 'dictionary' of key value pairs where the key is a
# LauncPad bug id and the value is the source package of interest.
#

from sys                                import argv, modules
from getopt                             import getopt

from lib.dbg                            import Dbg
from lib.test_attributes                import TestAttributes
from lib.utils                          import dump

# Exit
#
class Exit():
    """
    If an error message has already been displayed and we want to just exit the app, this
    exception is raised.
    """
    pass

# Gatherer
#
class Gatherer():
    """
    This class/script examines all 'open' bugs. If a given bug was filed against a
    version of Ubuntu that is no longer supported, change the status of that bug
    to "Won't Fix" and add a comment explaining why it was marked as such.
    """

    # __init__
    #
    def __init__(self, cfg):
        self.cfg    = cfg

    # main
    #
    def main(self):
        Dbg.enter("Gatherer.main")

        try:
            attributes = TestAttributes(self.cfg)
            dump(attributes.gather())

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        except Exit:
            pass

        Dbg.leave("Gatherer.main")
        return


if __name__ == '__main__':
    defaults = {}
    defaults['app_name'] = argv[0]

    me = modules[__name__]
    try:
        optsShort = ''
        optsLong  = ['help', 'vh-name=']
        opts, args = getopt(argv[1:], optsShort, optsLong)
        setattr(me, 'vh_name', '')
        for opt, val in opts:
            if (opt == '--help'):
                print(" Usage: gather-attributes [--vh-name=<virtual-host-name>]\n")
                raise Exit()

            elif opt in ('--vh-name'):
                setattr(me, 'vh_name', val)

        app = Gatherer(me)
        app.main()

    except Exit:
        pass


# vi:set ts=4 sw=4 expandtab:

