#!/bin/sh

# job-postprocessing
#
# This shell script does any benchmark processing, gathers the autotest results and gets them back to
# the jenkins server.
#

#
# For benchmarks, process the results and send them for archiving
#
if [ "$HAS_METRICS" = "true" ]; then
    pwd
    autotest/client/tools/process_metrics.py | sudo tee autotest/client/results/$BUILD_TAG-$BUILD_ID-$TEST_NAME.json > /dev/null
    scp autotest/client/results/$BUILD_TAG-$BUILD_ID-$TEST_NAME.json $JENKINS_SERVER:$JENKINS_HOME/metrics/
fi

# Process the results
#
sudo autotest/client/tools/results2junit.py autotest/client/results/default > $WORKSPACE/autotest-results.$TEST_NAME.xml

# Gather up the files that will be helpful is any of the tests fail.
#
sudo chown -R $USER.$USER autotest/client/results
tar jcf $TEST_NAME-results.tbz2 autotest/client/results

# Only the jobs that the Kerne Team runs should have this envrironment
# variable set. This is so we can do things in our scripts that we don't
# want QA doing.
#
if [ -n "$KERNEL_TEAM_JOB" ]; then
    # We want to copy as much of the build results files to the build artifacts
    # on the server. This is for debugging test failures.
    #
    ssh $JENKINS_SERVER mkdir -p $JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_ID/archive
    scp -r autotest/client/results $JENKINS_SERVER:$JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_ID/archive/$TEST_NAME
fi


# vi:set ts=4 sw=4 expandtab:
