#!/bin/sh

# kernel-tests-runner
#
# The master, control script for running the tests the Ubuntu kernel
# team wants QA to run as part of their regression tests.
#

CDIR="`dirname $0`"

# Call python script - which does:
#    Read test (and collections) names from env KERNEL_TEST_LIST
#    Expand any test collections
#    Make tests to see which control files should be run
#    Create a batch file containing setup
#    Create a batch file setting environment variables for tests to run
./$CDIR/kernel-test-expander

# run presetup, which was created by kernel-test-expander
. ./presetup

# WORKSPACE may be passed in from the top-level jenkins job
if [ -z "$WORKSPACE" ]; then
    WORKSPACE=/tmp/workspace
    mkdir -p $WORKSPACE
fi

echo ">>>  test-attributes begin"
./$CDIR/gather-attributes $VIRTUAL_HOST_NAME | tee test-attributes.json
echo ">>>  test-attributes end"

set +e # We want _all_ the tests to run even if one of them errors out.

# run run-tests, which was created by kernel-test-expander
. ./run-tests

# Stitch all the individual test results files together.
#
autotest/client/tools/glue_testsuites $WORKSPACE/*.xml > $WORKSPACE/kernel-results.xml

# vi:set ts=4 sw=4 expandtab:
