#!/bin/sh

# pre-testing-setup
#
# This script must be run before running the test-runner script. This
# script will perform all necessary configuration required by the
# tests that test-runner runs.
#
# The types of configuration performed:
#   1. Installing all required packages.
#   2. Creating any temp directories.
#

# QRT tests:
sudo apt-get install -y build-essential libcap2-bin gcc-multilib gdb gawk execstack exim4 libcap-dev

# ecryptfs:
sudo apt-get install -y libglib2.0-dev intltool keyutils libkeyutils-dev libpam0g-dev libnss3-dev libtool acl xfsprogs btrfs-tools


# xfstests:
sudo apt-get install -y uuid-dev xfslibs-dev xfsdump autoconf kpartx libtool python-xattr libacl1-dev libaio-dev quota bc libdm0-dev btrfs-tools attr

sudo mkdir -p /media/xfsmount
sudo adduser --quiet --disabled-password -gecos "XFS test user,,," fsgqa || true

# partition the second drive for use with xfstests
#
TARGET=/dev/sdb

sudo parted $TARGET print
sudo parted $TARGET rm -s 1
sudo parted $TARGET rm -s 2
sudo parted $TARGET mklabel -s gpt
sudo parted $TARGET mkpart -s p1 ext4 1MiB 1000MiB
sudo parted $TARGET mkpart -s p2 ext4 1001MiB 2000MiB
sudo parted $TARGET print

# vi:set ts=4 sw=4 expandtab:
