#!/bin/bash
#

# Push the kernel-tester script to a remote system via scp and then
# run the script.
#

#set -x

usage()
{
    echo "usage: remote [option] sut"
    echo " "
    echo "-h | --help"
    echo "    Prints this help message and exits. "
    echo " "
    echo "--kernel-test-list"
    echo "    A list of the tests to be run. The tests are separated by whitespace."
    echo " "
    echo "--kernel-test-options"
    echo "    Options that are to be passed down to the tests as 'autotest arguments'."
    echo " "
    echo "--test-repository-host"
    echo "    Hostname or IP address of the system that has the test files."

    exit 1
}

# This variable is unique to the jobs that the kernel team runs on their
# jenkins server.
#
export KERNEL_TEAM_JOB="true"
export KERNEL_TEST_LIST="iperf"
export KERNEL_TEST_OPTIONS="{}"
export TEST_REPOSITORY_HOST=kernel-jenkins
export VIRTUAL_HOST_NAME=""

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            usage
            ;;

        --kernel-test-list=*)
            export KERNEL_TEST_LIST=$(echo $1 | cut -d= -f2)
            ;;

        --kernel-test-options=*)
            export KERNEL_TEST_OPTIONS=\"$(echo $1 | sed -e 's/--kernel-test-options=//')\"
            ;;

        --test-repository-host=*)
            export TEST_REPOSITORY_HOST=$(echo $1 | cut -d= -f2)
            ;;

        --virtual-host-name=*)
            export VIRTUAL_HOST_NAME=$(echo $1 | cut -d= -f2)
            ;;

        --*)
            echo *** Error: The specified option $1 is not recognized
            usage
            ;;

        *)
            SUT=$1
            ;;
    esac
    shift
done

set -e

export SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"

# Push the tests and the kernel team infrastructure to the SUT.
#
ssh $SSH_OPTIONS $SUT sudo rm -rf autotest kernel-testing

rsync -e "ssh $SSH_OPTIONS" -ar --exclude=.git $HOME/autotest/ $SUT:autotest/
rsync -e "ssh $SSH_OPTIONS" -ar --exclude=.git $HOME/autotest-client-tests/* $SUT:autotest/client/tests/
rsync -e "ssh $SSH_OPTIONS" -ar --exclude=.git $HOME/autotest-client-virt-tests/* $SUT:autotest/client/tests/virt/
rsync -e "ssh $SSH_OPTIONS" -ar --exclude=.git $HOME/kernel-testing/ $SUT:./kernel-testing/

export TIMESTAMP="\"`date +'%A, %e. %B %Y %H:%M %Z'`\"" # Need the time reported in a specific format for final reporting
export NOW="\"`date`\""                                 # Set the date on the SUT to the same as jenkins
ssh $SSH_OPTIONS $SUT sudo date -s "$NOW"
ssh $SSH_OPTIONS $SUT _TS_="$TIMESTAMP" JOB_NAME=$JOB_NAME KERNEL_TEST_OPTIONS=$KERNEL_TEST_OPTIONS python kernel-testing/runner $KERNEL_TEST_LIST
