#!/bin/sh
set -e

# For local testing
#
rm -rf autotest kernel-test-results
if [ -z "$ADT_ARTIFACTS" ]; then
    ADT_ARTIFACTS="."
fi

# Pull the sources down and get them put into the autotest tree where
# they belong.
#
git clone git://kernel.ubuntu.com/ubuntu/autotest
git clone git://kernel.ubuntu.com/ubuntu/autotest-client-tests
git clone git://kernel.ubuntu.com/ubuntu/autotest-client-virt-tests
git clone git://kernel.ubuntu.com/ubuntu/autotest-docker


rmdir autotest/client/tests/
mv autotest-client-tests/ autotest/client/tests

rmdir autotest/client/tests/virt
mv autotest-client-virt-tests/ autotest/client/tests/virt

rmdir autotest/client/tests/docker
mv autotest-docker/ autotest/client/tests/docker

set +e
kernel-testing/dep8-runner
RESULT=$?

# Collect the artifacts
#
tar cJf $ADT_ARTIFACTS/results.tar.xz kernel-test-results

exit $RESULT
