#!/usr/bin/env python

import sys, os

clpath = os.path.join(os.path.dirname(sys.argv[0]), "debian/changelog")

with open(clpath, 'r') as f:
  fl = f.readline()

print fl[fl.find("(")+1:fl.find(")")]
