#!/usr/bin/env python
#

import sys

def main(argv):

    for fname in argv[0:]:
        with open(fname, 'r') as f:
            content = f.read()

        fixed = content.decode("utf-8").replace(u"\u0008", "*").encode("utf-8")
        fixed = fixed.decode("utf-8").replace(u"\u0000", "*").encode("utf-8")
        print(fixed)

if __name__ == '__main__':
    main(sys.argv[1:])

# vi:set ts=4 sw=4 expandtab:
