#!/bin/bash

TARGET_HOST=$1

timeout=0
is_started=0
date
while [ $is_started -ne 1 ]; do
    set +e
    # force connect/disconnect
    ssh -qf -o StrictHostKeyChecking=no jenkins@$TARGET_HOST exit
    if [ $? -eq 0 ]; then
        echo "Ubuntu started"
        is_started=1
    else
        sleep 60
        let timeout=timeout+1
        if [ $timeout -ge 60 ]; then
            echo "Aborting installation. $timeout_limit timeout reached."
            date
            exit 1
        fi
    fi
    set -e
done

# vi:set ts=4 sw=4 expandtab:
